### ISSUE TITLE
Not highlight entity.name.class

### ISSUE THREAD

**Issue by jk4837** [colinta/zenburn#5]
Hi,

I found that class names are not highlighted in the built-in java syntax.
![image](https://user-images.githubusercontent.com/10583408/51979026-f4c22700-24c6-11e9-904c-58db38069e19.png)

Its scope name is `entity.name.class`, but `Class type name` in zenburn.tmTheme currently only supports:
- entity.name.type
- entity.name.type.class 
- entity.other.attribute-name.class.css 
- support.class

Can you add `entity.name.class` into the list? Thanks!

**Comment by colinta** [comment]
Sure - added in 2.6.0
