### ISSUE TITLE
Theme is broken in Sublime Text

### ISSUE THREAD

**Issue by ahamadanees-pa** [colinta/zenburn#6]
Colour scheme is great. But when I apply the theme, this is how it looks like:

![screenshot_issue_zenburn](https://user-images.githubusercontent.com/47503781/58765807-75d41c80-8594-11e9-9bca-0a9e2ec775cb.png)

### Environment

```text

Sublime Text:

* channel: stable
* version: 3207
* platform: linux
* architecture: x64

Dependency versions:

* mdpopups: Version could not be acquired!
* markdown: 2.6.11
* pygments: 2.1a0
* jinja2: 2.8
```

**Comment by wboka** [comment]
#4 Looks like it is up to the community.

**Comment by colinta** [comment]
That would be great – I can't reproduce this error locally.

**Comment by wboka** [comment]
I believe this is caused by the paths not being found. `Theme - Default/arrow_right.png` Was the theme made for Sublime Text 2 or 3? I don't think Sublime Text 3 has a `Theme -Default` directory anymore.

**Comment by colinta** [comment]
I'm wondering why this works on my own computer; I have a `Theme - Default.sublime-package`, but opening that (as a .zip) I don't see any of these images in there!  I'll investigate that.  Good find.

**Comment by wboka** [comment]
Looks like the `Theme - Default` moved some files around during one of the updates. The icons are in a few sub-directories.

I'm using version 3.2.1 Build 3207 on Windows 10

**Comment by colinta** [comment]
Actually, I'm just going to delete this theme altogether; the real value is in the color scheme (in prefs: `"color_scheme": "Packages/zenburn/zenburn.tmTheme"`), and the Adaptive theme looks great w/ zenburn (`"theme": "Adaptive.sublime-theme"`)
