### ISSUE TITLE
minor issue

### ISSUE THREAD

**Issue by jods239** [colinta/zenburn#7]
![fileName](https://user-images.githubusercontent.com/15861323/65536694-37c48500-df04-11e9-8960-91635adc5b1c.png)
Every time I start subl I get this error. Sometimes the text background is white (foreground black). After clicking the error window everything appears to be normal.
Sublime Text Build 3207
Linux: Debian testing

**Comment by colinta** [comment]
Is there anything else in `InactivePanes` that would be a clue?  I don't know what this is.

**Comment by jods239** [comment]
No other files or directories there. Maybe give uninstall en reinstall a try?

**Comment by jods239** [comment]
After reinstall, deleting InactivePanes, restart. Everything seems to be ok.

**Comment by colinta** [comment]
Cool!  If everything seems OK please close this issue when you get a chance.

**Comment by jods239** [comment]
I removed InactivePanes wich is a package (https://github.com/SublimeText/InactivePanes)
There is probably an interference.
